title: Kevin Avicenna Widiarto 
logo: "/images/profile.png?raw=true" 
description: > 
  <br><br>
  Hello, My Name Is Kevin Avicenna. I'm a Student At University Muhammadiyah Surakarta. I'm Interested In Data And Cyber Fields 
  <br><br>
  <a href="https://www.linkedin.com/in/kevinavicenna/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-YC15RBLEHX # your Google Analytics tracking ID here
