title: Kevin Avicenna Widiarto 
logo: "/images/profile.png?raw=true" 
description: > 
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/kevinavicenna/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-YC15RBLEHX # your Google Analytics tracking ID here
