title: Kevin Avicenna Widiarto 
logo: "/images/profile.png?raw=true" 
description: > 
  <p align="center">
  <a href="pdf/resumekevin.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kevinavicenna/">LinkedIn</a> |
  <a href="https://github.com/kevinavicenna">GitHub</a>
  </p>
  
  <p align="justify">
  Hello, My Name Is Kevin Avicenna. I'm a Student At University Muhammadiyah Surakarta. I'm Interested In Data And Cyber Fields
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-YC15RBLEHX # your Google Analytics tracking ID here
